# Библиотека Numpy

In [74]:
L = range(10000)
%timeit [i**2 for i in L]

719 µs ± 14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [75]:
import numpy as np
L = np.arange(10000)
%timeit L**2

7.99 µs ± 1.67 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Импорт библиотеки

In [76]:
#Стандартный способ, которого желательно всюду придерживаться
import numpy as np

In [77]:
#Другие возможные варианты
import numpy
from numpy import sort, sqrt, mean
from numpy import *

In [78]:
#Так делать не нужно
from numpy import max #будет путаница со стаднартной функцией max в питоне
import numpy as some_magic_liblary

### Массив ndarray

Numpy умеет хранить в памяти массивы **однородных** значений (int, float, строки ограниченной длины, указатели на другие объекты).

Объект массив имеет несколько важных параметров:
* shape - размерность массива
* dtype - тип элементов массива
* stride - описание того, как считывать массив

Пример одномерного массива:

In [79]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Параметры массива:

In [80]:
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(10,)
int64
(8,)


Пример двумерного массива:

In [81]:
arr_2d = np.arange(10, dtype=float).reshape((2,-1))
arr_2d

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Параметры массива:

In [82]:
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(2, 5)
float64
(40, 8)


### Способы задания массивов

In [83]:
# Create an array of evenly-spaced values
np.arange(10, 25, 5)

array([10, 15, 20])

In [84]:
# Create an array of evenly-spaced values
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [85]:
# Create an array of ones
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
# Create an array of zeros
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [87]:
# Create an array with random values
np.random.random((2, 2))

array([[0.50010311, 0.61262494],
       [0.98648839, 0.92929541]])

In [88]:
# Create a full array
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [89]:
# Create a diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Индексация элементов массива

In [90]:
a = np.arange(10)
print(a[0])
print(a[[3, -1]])
print(a[3::2])
print(a[6: -2])
print(a[:-3])

0
[3 9]
[3 5 7 9]
[6 7]
[0 1 2 3 4 5 6]


Индексация многомерных массивов:

In [91]:
a = np.diag(np.arange(3))
print(a[1, 2])
print(a[1:])

0
[[0 1 0]
 [0 0 2]]


Бывает удобно использовать маски:

In [92]:
a = np.arange(10, 20)
mask = a % 3 == 0
print(mask)

[False False  True False False  True False False  True False]


Выбор элементов по маске

In [93]:
print(a[mask])

[12 15 18]


Операции над элементами по маске

In [94]:
a[a%3 == 0] = -1
print(a)

[10 11 -1 13 14 -1 16 17 -1 19]


### Арифметические операции выполняются поэлементно

In [95]:
a = np.arange(1, 4)
print(a + 1)
print(2**a)
print(a**2)

[2 3 4]
[2 4 8]
[1 4 9]


### Функции над массивами

In [96]:
a = np.array([1, 2, 3])
print(np.sum(a), np.sin(a), np.mean(a), np.std(a), np.min(a))

6 [0.84147098 0.90929743 0.14112001] 2.0 0.816496580927726 1


Многие функции являются  методами массива:

In [97]:
a.mean() == np.mean(a)

np.True_

Для многомерных массивов можно управлять вдоль какой размерности применять метод:

In [98]:
a=np.arange(24).reshape((2, 3, 4))
print(np.mean(a, axis=(-2, -1)))

[ 5.5 17.5]


Сортировка элементов:

In [99]:
a = np.random.randn(5)
print(np.sort(a), np.argsort(a))

[-0.98442411 -0.51053573 -0.19703798  0.04320828  1.41383537] [3 2 0 4 1]


### Сложение массивов

In [100]:
a = np.floor(10 * np.random.rand(2, 2))
print('Array a\n', a)

b = np.floor(10 * np.random.rand(2, 2))
print('Array b\n', b)

print('\n--Concatenate a and b vertically --\n')
print(np.vstack((a, b))) # сложение по вертикали
print('\n--Concatenate a and b horizontally--\n')
print(np.hstack((a, b))) # сложение по горизонтали

Array a
 [[5. 7.]
 [2. 2.]]
Array b
 [[6. 8.]
 [2. 4.]]

--Concatenate a and b vertically --

[[5. 7.]
 [2. 2.]
 [6. 8.]
 [2. 4.]]

--Concatenate a and b horizontally--

[[5. 7. 6. 8.]
 [2. 2. 2. 4.]]


### Array broadcasting
Схема ниже показывает, как происходит скложение массивов. Если shape у массивов не совпадают, то массив меньшей размерности "естественным образом" дополняется до большей размерности.

<img src="http://scipy-lectures.org/_images/numpy_broadcasting.png" width="600"/>

In [101]:
x = np.ones((3, 4))
y = np.arange(4)

# Add `x` and `y`. Note that `x` and `y` have different shapes.
print(x.shape, y.shape)
print(x + y)

(3, 4) (4,)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Как прибавить массив ко всем столбцам матрицы?

In [102]:
x = np.ones((3, 4))
y = np.arange(3)

print(x + y.reshape(-1, 1))

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [103]:
#правильный способ
print(x + y.reshape(-1, 1))

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


### Задачи для самостоятельной практики
100 numpy exersices https://github.com/rougier/numpy-100

rus версия https://github.com/alex-sokolov2011/100_Numpy_exercises_Rus_ver


### Домашняя работа
Задача минимум -- решить без использования циклов for/while. Задача максимум -- решить в одну строку (строка с созданием массива, к которому формулируется задание, не учитывается).

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [104]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [105]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [106]:
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [107]:
Z = np.random.random((5, 5))
Z_norm = Z - Z.mean(axis=1, keepdims=True)
print("Средние по строкам (должны быть ~0):", Z_norm.mean(axis=1))

Средние по строкам (должны быть ~0): [ 2.22044605e-17 -2.22044605e-17 -4.44089210e-17  0.00000000e+00
  2.22044605e-17]


5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [108]:
Z = np.random.random((10, 3))
closest_indices = np.argmin(np.abs(Z - 0.5), axis=1)
result = Z[np.arange(Z.shape[0]), closest_indices]
print(result)

[0.32931382 0.20609367 0.43379932 0.50501214 0.50265862 0.58759965
 0.63671062 0.50211601 0.51194353 0.45478827]


6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [109]:
Z = np.random.random((6, 6))
result = Z.sum(axis=1) / Z.max(axis=0)
print(result)

[2.52731421 3.13676946 2.9006533  6.11387096 2.6827853  4.26420783]


7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [110]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero_mask = (x[:-1] == 0)
result = np.max(x[1:][zero_mask])
print(result)

5


8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [111]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
np.add.at(x, i, 1)
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


9. Задайте два массива
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и
b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [112]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])

diff = np.abs(a[..., np.newaxis] - b)

nearest_idx = np.argmin(diff, axis=-1)

result = b[nearest_idx]
print(result)

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


10. Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [113]:
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])
result = np.convolve(a, np.ones(3)/3, mode='valid')
print(result)

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]


Задача со звездочкой.

Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.

Пример входа:
```
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
```

Ожидание на выходе:
```
array([[ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5],
       [15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5],
       [25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5]])
```

In [114]:
Z = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

result = (Z[:-1, :-1] + Z[:-1, 1:] + Z[1:, :-1] + Z[1:, 1:]) / 4
print(result)

[[ 5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5]
 [15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5]
 [25.5 26.5 27.5 28.5 29.5 30.5 31.5 32.5 33.5]]


### Read more

[http://scipy-lectures.org/intro/numpy/array_object.html](http://scipy-lectures.org/intro/numpy/array_object.html)

[https://docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html)
